version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_restaurant
    image: debezium/example-postgres # essa versao vem com as configuracoes necessarias para o connector do debezium
    environment:
      POSTGRES_USER: #
      POSTGRES_PASSWORD: #
    ports:
      - "5436:5436"
  postgres_marketplace:
    container_name: postgres_marketplace_restaurant
    image: postgres:12.2
    environment:
      POSTGRES_USER: #
      POSTGRES_PASSWORD: #
    ports:
      - "5435:5436"